//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSMVCWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Associate
    {
        public int AssociateId { get; set; }
        public string AssociatePwd { get; set; }
        public int RoleId { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
